name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: BASE_URL=https://dev.transfans.com/login ADMIN_URL=https://admin.dev.transfans.com/ CREATOR_NAME=rezinazina@internetkeno.com CREATOR_PASSWORD='Qweasdzxc123?' ADMIN_NAME=admin2@gmail.com ADMIN_PASSWORD='M0VtYmVk' USER_NAME=usertf2@diginey.com USER_PASSWORD='Qweasdzxc123?' npx playwright test --workers=4
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
