name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Set up xvfb
        run: sudo apt-get install xvfb
      - name: Run Playwright tests
        env:  # Set environment variables from secrets
          BASE_URL: ${{ secrets.DEV_URL }}
          ADMIN_URL: ${{ secrets.ADMIN_DEV_URL }}
          CREATOR_NAME: ${{ secrets.CREATOR_DEV_NAME }}
          CREATOR_PASSWORD: ${{ secrets.CREATOR_DEV_PASSWORD }}
          ADMIN_NAME: ${{ secrets.ADMIN_DEV_NAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_DEV_PASSWORD }}
          USER_NAME: ${{ secrets.USER_DEV_NAME }}
          USER_PASSWORD: ${{ secrets.USER_DEV_PASSWORD }}
        run: (xvfb-run -a npx playwright test > test-output.log 2>&1) || echo "Playwright tests failed!"
      - name: Generate Test Summary
        run: |
          grep -E '✓|✕' test-output.log > test-summary.txt
      - name: Install Allure
        run: npm install -g allure-commandline
      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: allure-report/
          retention-days: 30
      - name: Send email with test summary
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Playwright Test Summary
          body: Here is the summary of Playwright tests.
          to: ${{ secrets.RECIPIENT }}
          from: ${{ secrets.MAIL_USERNAME }}
          attachments: test-summary.txt
